FEATURES = [
    "invoice_amount",
    "submission_hour",
    "supplier_invoice_count_30d",
    "supplier_avg_amount_90d",
    "invoice_amount_zscore",
    "duplicate_invoice_flag",
    "split_invoice_flag",
    "late_night_submission_flag",
    "supplier_age_days",
    "supplier_risk_score",
    "blacklisted_flag",
    "avg_invoice_amount",
    "annual_budget",
    "ocr_total_extracted",
    "image_tamper_flag",
    "amount_to_supplier_90d_avg_ratio",
    "amount_to_supplier_avg_ratio",
    "amount_diff_supplier_90d_avg",
    "supplier_age_years",
    "invoice_day_of_week",
    "weekend_invoice_flag",
    "outside_business_hours_flag",
    "invoice_to_department_budget_ratio",
    "log_invoice_amount",
    "image_metadata_available_flag",
    "invoice_ocr_amount_diff",
    "invoice_ocr_relative_diff",
    "payment_terms_NET30",
    "payment_terms_NET60",
    "payment_terms_NET90",
    "invoice_type_GOODS",
    "invoice_type_SERVICES",
]

ID_COLUMN = "invoice_id"
REQUIRED_COLUMNS = [ID_COLUMN] + FEATURES

BINARY_FEATURES = {
    "duplicate_invoice_flag",
    "split_invoice_flag",
    "late_night_submission_flag",
    "blacklisted_flag",
    "image_tamper_flag",
    "weekend_invoice_flag",
    "outside_business_hours_flag",
    "image_metadata_available_flag",
    "payment_terms_NET30",
    "payment_terms_NET60",
    "payment_terms_NET90",
    "invoice_type_GOODS",
    "invoice_type_SERVICES",
}
